---
name: publish documentation
on: workflow_dispatch
env:
  PYTHON_VERSION: "3.12"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install poetry
        shell: bash
        run: |
          sudo apt install python3-poetry
      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install --all-extras
      - name: Build documentation
        shell: bash
        run: |
          python -m poetry run -C docs make html
      - name: Publish docs on github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: $${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          force_orphan: true
